name: "Artifacts Example 2"
description: "An example pipeline from Chris that builds, tests, and packages a Python library using Bazel."
emoji: ":smile:"
languages:
  - "Shell"
  - "Bash"
steps:
  - label: ":pipeline:"
    command: |
      buildkite-agent pipeline upload
      echo "haha"
